---
output: 
  pdf_document:
    includes:
      in_header: header.tex
---

\singlespacing

# 

This appendix contains the R script for Simulation 1.

```{r, eval=FALSE, echo=TRUE}
### Model code for simulation 1

## create contingency task trials

create_trials <- function(A, B, C, D, vector_length, shuffle=FALSE){
  
  event_frequencies <- rep(c(1,2,3,4), times = c(A,B,C,D))
  
  event_pairs <- matrix(c(rep(c(1,1,1), each = vector_length),
                          rep(c(1,0,1), each = vector_length),
                          rep(c(0,1,1), each = vector_length),
                          rep(c(0,0,1), each = vector_length)),
                      ncol= vector_length*3,
                      byrow=TRUE)
  
  event_matrix <- event_pairs[event_frequencies,]
  
  if(shuffle==FALSE) {return(event_matrix)
    }else{
    return(event_matrix[sample(1:length(event_frequencies)),])
    }
  
}

## Run the model function

run_model <- function(trials,probe){
  memory <- trials

#probe memory with cue only

  similarities <- c()
  for(i in 1:dim(memory)[1]){
    similarities[i] <- lsa::cosine(probe,memory[i,])
  }
  similarities[is.nan(similarities)]<-0
  
  # generate echo
  weighted_memory <- memory*(similarities^3)
  echo <- colSums(weighted_memory)
  
  return(echo)
}

### DEFINE conditions

conditions <- list(list(outcome_density = .2,
                        delta_p = 0,
                        frequencies = c(6,24,6,24)),
                   list(outcome_density = .8,
                        delta_p = 0,
                        frequencies = c(24,6,24,6)),
                   list(outcome_density = .33,
                        delta_p = .467,
                        frequencies = c(17,13,3,27)),
                   list(outcome_density = .67,
                        delta_p = .467,
                        frequencies = c(27,3,13,17))
                   )

model_data<-data.frame() #initialize data frame

## Run the model across conditions

for(i in 1:4){
  trials <- create_trials(A=conditions[[i]]$frequencies[1],
                          B=conditions[[i]]$frequencies[2],
                          C=conditions[[i]]$frequencies[3],
                          D=conditions[[i]]$frequencies[4],
                          vector_length = 10,
                          shuffle=TRUE)
  model_output <- run_model(trials=trials,probe = rep(c(1,0,1),each=10))
  sim_data <- data.frame(outcome_density = conditions[[i]]$outcome_density,
                         delta_p = conditions[[i]]$delta_p,
                         expectation = model_output[11])
  model_data <- rbind(model_data,sim_data)
}

# print table
#knitr::kable(model_data)
```

```{r, eval=FALSE, echo=TRUE}
# plot
library(ggplot2)

ggplot(model_data,aes(x=outcome_density,
                      y=expectation,
                      group=delta_p,
                      color=delta_p))+
  geom_line()+
  geom_point()
```

\newpage

\singlespacing

# 

This appendix contains the R script for Simulation 2.

```{r, eval=FALSE, echo=TRUE}
## Simulation 2

run_model_activations <- function(trials,probe,resonance){
  memory <- trials

#probe memory with cue only

  similarities <- c()
  for(i in 1:dim(memory)[1]){
    similarities[i] <- lsa::cosine(probe,memory[i,])
  }
  similarities[is.nan(similarities)] <- 0

  # get activations
  activations <- sum(similarities^resonance)

  return(activations)
}

# frequency judgment simulation
freq_model_data <- data.frame() #initialize data frame

## Run the model across conditions

for(tau in c(1,3,9,15,21,27)){
  for(i in 1:4){
    trials <- create_trials(A=conditions[[i]]$frequencies[1],
                            B=conditions[[i]]$frequencies[2],
                            C=conditions[[i]]$frequencies[3],
                            D=conditions[[i]]$frequencies[4],
                            vector_length = 10,
                            shuffle=TRUE)
    
    freq_A <- run_model_activations(trials=trials,
                                    probe = rep(c(1,1,1),each=10),
                                    resonance = tau)
    freq_B <- run_model_activations(trials=trials,
                                    probe = rep(c(1,0,1),each=10),
                                    resonance = tau)
    freq_C <- run_model_activations(trials=trials,
                                    probe = rep(c(0,1,1),each=10),
                                    resonance = tau)
    freq_D <- run_model_activations(trials=trials,
                                    probe = rep(c(0,0,1),each=10),
                                    resonance = tau)
    
    sim_data <- data.frame(outcome_density = conditions[[i]]$outcome_density,
                           delta_p = conditions[[i]]$delta_p,
                           expectation = (freq_A/(freq_A+freq_B)) - (freq_C/(freq_C+freq_D)),
                           resonance = tau)
    
    freq_model_data <- rbind(freq_model_data,sim_data)
  }
}
```

```{r, eval=FALSE, echo=TRUE}
# plot
library(latex2exp)
freq_model_data$delta_p <- as.factor(freq_model_data$delta_p)

ggplot(freq_model_data,aes(x=outcome_density,
                      y=expectation,
                      group=delta_p,
                      color=delta_p,
                      shape=delta_p))+
  geom_line()+
  geom_point()+
  xlab("Probability of Outcome")+
  ylab(TeX(r'(Simulated $\Delta$P)'))+
  coord_cartesian(xlim=c(0,1))+
  scale_color_discrete(name = expression(Delta~P))+
  scale_shape_discrete(name = expression(Delta~P))+
  theme_classic(base_size=12)+
  facet_wrap(~resonance)

```